CREATE TABLE IF NOT EXISTS products(
  id TEXT PRIMARY KEY, name TEXT NOT NULL, price REAL NOT NULL,
  description TEXT DEFAULT '', images TEXT DEFAULT '[]',
  colors TEXT DEFAULT '[]', position INTEGER DEFAULT 0,
  upc TEXT DEFAULT '');
INSERT OR REPLACE INTO products VALUES('pinking-shears-huitong','Hui Tong Strong & Sharp Pinking Shears — Serrated & Scalloped Fabric Scissors',17.39,'Effortlessly cuts denim, leather, and silk — clean from first tooth to last. Hand-sharpened by master craftsmen; high-carbon stainless steel resists rust and stays sharp 3x longer than standard shears. The precision serrated blade creates a smooth, finished edge that prevents fraying and reduces bulk.','["images/pinking-shears-1.jpg", "images/pinking-shears-2.jpg", "images/pinking-shears-3.jpg", "images/pinking-shears-4.jpg", "images/pinking-shears-5.jpg"]','[{"name": "Serrated 5mm", "hex": ""}, {"name": "Serrated 3mm", "hex": ""}, {"name": "Serrated 7mm", "hex": ""}, {"name": "Scalloped 5mm", "hex": ""}, {"name": "Scalloped 7mm", "hex": ""}, {"name": "Wavy 18mm", "hex": ""}]',0,'');
INSERT OR REPLACE INTO products VALUES('pro-tailor-8','Professional 8" Tailor Scissors',32.99,'Forged from Japanese stainless steel with a razor-sharp convex edge. Balanced for all-day cutting on fabric, leather and denim.','[]','[{"name": "Classic Silver", "hex": "#c9c9c9"}, {"name": "Gold", "hex": "#d4af6a"}, {"name": "Matte Black", "hex": "#2b2b2b"}]',1,'');
INSERT OR REPLACE INTO products VALUES('embroidery-4','4" Embroidery Detail Scissors',14.99,'Fine pointed tips for thread work, embroidery and precision craft cuts. Includes a protective leather sheath.','[]','[{"name": "Rose Gold", "hex": "#e0a899"}, {"name": "Silver", "hex": "#c9c9c9"}]',2,'');
INSERT OR REPLACE INTO products VALUES('kitchen-shears','Heavy-Duty Kitchen Shears',21.99,'Come-apart blades for easy cleaning. Cuts poultry, herbs and packaging; built-in bottle opener and nutcracker.','[]','[{"name": "Black", "hex": "#2b2b2b"}, {"name": "Red", "hex": "#b03a2e"}]',3,'');
INSERT OR REPLACE INTO products VALUES('hair-cutting-6','6" Barber Hair Cutting Shears',45.99,'440C steel with tension adjustment screw and removable finger rest. Salon-grade sharpness for clean, quiet cuts.','[]','[{"name": "Silver", "hex": "#c9c9c9"}, {"name": "Rainbow", "hex": "#9b7ec4"}, {"name": "Matte Black", "hex": "#2b2b2b"}]',4,'');
INSERT OR REPLACE INTO products VALUES('pinking-shears','9" Pinking Shears',18.99,'Zigzag edge prevents fabric fraying. Comfortable soft-grip handles sized for extended sewing sessions.','[]','[{"name": "Silver", "hex": "#c9c9c9"}, {"name": "Teal", "hex": "#3f8f8b"}]',5,'');
INSERT OR REPLACE INTO products VALUES('craft-set-3','Craft Scissors 3-Piece Set',26.99,'Three sizes (5", 7", 8.5") for paper, vinyl and mixed-media craft. Titanium-coated blades resist adhesive buildup.','[]','[{"name": "Pastel Mix", "hex": "#d8b4c8"}, {"name": "Bold Mix", "hex": "#4a6fa5"}]',6,'');
